# Generated by Django 5.0.7 on 2024-11-18 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuOptonXroles',
            new_name='MenuOptionXRoles',
        ),
        migrations.RenameModel(
            old_name='ParametesXmenuOptions',
            new_name='ParametersXMenuOptions',
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rnc', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('representative', models.ForeignKey(blank=True, db_column='representative', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_representative', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'BUSINESS',
            },
        ),
    ]
