# Generated by Django 5.0.7 on 2024-11-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_menuoptonxroles_menuoptionxroles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='rnc',
            field=models.CharField(max_length=11),
        ),
    ]
