# Generated by Django 5.0.7 on 2024-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_business_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
