# Generated by Django 5.0.7 on 2024-12-12 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_id', models.AutoField(primary_key=True, serialize=False)),
                ('termination_type', models.CharField(choices=[('D', 'Despedido'), ('R', 'Renunciado'), ('F', 'Fallecido')], max_length=1)),
                ('reason', models.TextField()),
                ('termination_date', models.DateField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_username', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Finalización de contrato',
                'verbose_name_plural': 'Finalización de contratos',
                'db_table': 'TERMINATION',
            },
        ),
    ]
