# Generated by Django 5.0.7 on 2024-12-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_termination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termination',
            name='termination_type',
            field=models.CharField(choices=[('D', 'Despedido'), ('R', 'Renunciado'), ('F', 'Fin contrato')], max_length=1),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_account', models.CharField(max_length=20, unique=True, verbose_name='Número de cuenta')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('account_type', models.CharField(choices=[('S', 'Ahorro'), ('C', 'Corriente'), ('N', 'Nómina')], max_length=1, verbose_name='Tipo de cuenta')),
                ('is_primary', models.BooleanField(default=False, verbose_name='¿Cuenta principal?')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_username', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'BANK_ACCOUNT',
            },
        ),
    ]
