# Generated by Django 5.0.7 on 2024-12-16 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_termination_termination_type_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del banco')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre corto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='bank', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_bank', to='users.bank', verbose_name='Banco'),
        ),
    ]
