# Generated by Django 5.0.7 on 2024-12-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_bankaccount_bank_name_bank_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelTable(
            name='bank',
            table='BANK',
        ),
    ]
