# Generated by Django 5.2 on 2025-05-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_bank_options_alter_bank_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, db_column='business_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_business', to='users.business'),
        ),
        migrations.AlterField(
            model_name='menuoptions',
            name='roles',
            field=models.ManyToManyField(related_name='%(class)s_roles', through='users.MenuOptionXRoles', through_fields=('option_id', 'rol_id'), to='users.roles'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='operations',
            field=models.ManyToManyField(related_name='%(class)s_roles', through='users.PermissionsRoles', through_fields=('rol_id', 'operation_id'), to='users.operations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='%(class)s_roles', through='users.RolesUsers', through_fields=('user_id', 'rol_id'), to='users.roles'),
        ),
    ]
