# Generated by Django 5.0.7 on 2024-10-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='is_additional_to_salary',
        ),
    ]
