# Generated by Django 5.0.7 on 2024-11-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0003_remove_leaves_reason_leaves_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='payment_type',
        ),
    ]
