# Generated by Django 5.0.7 on 2024-11-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0004_remove_leaves_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
