# Generated by Django 5.0.7 on 2024-11-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('time_management', '0005_overtime_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='concept',
            field=models.ForeignKey(blank=True, db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_concept', to='payroll.concept'),
        ),
    ]
