# Generated by Django 5.0.7 on 2024-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0006_overtime_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='state',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('D', 'Completada')], default='A', max_length=1),
        ),
    ]
