# Generated by Django 5.0.7 on 2024-11-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0007_alter_leaves_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaves',
            options={'ordering': ['-leave_id'], 'verbose_name': 'Vacaión, Permiso y Aucencia', 'verbose_name_plural': 'Vacaiones, Permisos y Aucencias'},
        ),
        migrations.AlterModelOptions(
            name='overtime',
            options={'ordering': ['-overtime_id'], 'verbose_name': 'Hora Extra', 'verbose_name_plural': 'Horas Extras'},
        ),
    ]
