# Generated by Django 5.0.7 on 2024-11-18 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='%(class)s_users', through='tasks.TaskXUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
