# Generated by Django 5.2 on 2025-04-21 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s_tags', through='tasks.TagXTasks', through_fields=('task', 'tag'), to='tasks.tags'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='%(class)s_users', through='tasks.TaskXUsers', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
