# Generated by Django 5.0.7 on 2024-10-26 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('concept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'CONCEPTS',
            },
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SFS', 'SFS - Seguro Familiar de Salud'), ('ISR', 'ISR - Impuesto Sobre la Renta'), ('AFP', 'AFP - Administradora de Fondos de Pensiones')], max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(max_length=250)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('concept', models.ForeignKey(blank=True, db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_concept', to='payroll.concept')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
                'db_table': 'DEDUCTIONS',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeductionXuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('deduction', models.ForeignKey(db_column='deduction_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deduction', to='payroll.deductions')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Retención por Usuario',
                'verbose_name_plural': 'Retenciones por Usuario',
                'db_table': 'DEDUCTION_X_USER',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period', models.IntegerField(default=1, unique_for_month=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pendiente'), ('F', 'Finalzada')], default='P', max_length=1, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'PAYROLL',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('payroll', models.ForeignKey(db_column='payroll_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payroll', to='payroll.payroll')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Entrada de Nómina',
                'verbose_name_plural': 'Entradas de Nómina',
                'db_table': 'PAYROLL_ENTRY',
                'ordering': ['payroll_entry_id'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Saldada')], default='A', max_length=1)),
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('B', 'Bono'), ('D', 'Descuento')], max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('concept', models.ForeignKey(blank=True, db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_concept', to='payroll.concept')),
                ('payroll_entry', models.ForeignKey(db_column='payroll_entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payroll_entry', to='payroll.payrollentry')),
            ],
            options={
                'verbose_name': 'Beneficio y Deducción',
                'verbose_name_plural': 'Beneficios y Deducciones',
                'db_table': 'ADJUSTMENT',
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('concept_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('operator', models.CharField(choices=[('+', 'Suma'), ('-', 'Resta')], default='-', max_length=1)),
                ('concept', models.ForeignKey(blank=True, db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_concept', to='payroll.concept')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('payroll', models.ForeignKey(db_column='payroll_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payroll', to='payroll.payroll')),
                ('payroll_entry', models.ForeignKey(db_column='payroll_entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payroll_entry', to='payroll.payrollentry')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Detalle de pago',
                'verbose_name_plural': 'Detalles de Pagos de nómina',
                'db_table': 'PAYROLL_PAYMENT_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('periods', models.IntegerField(choices=[(1, 'Mensual'), (2, 'Quincenal'), (4, 'Semanal')], default=1)),
                ('autopay', models.BooleanField(default=False)),
                ('deduction_period', models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (2, 'Tercero'), (4, 'Cuarto')], default=2, help_text='Período en el que se deben hacer los descuentos de ley')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Configuración de Nómina',
                'verbose_name_plural': 'Configuraciones de Nómina',
                'db_table': 'PAYROLL_SETTINGS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='deductions',
            constraint=models.UniqueConstraint(fields=('name', 'percentage'), name='unique_deduction'),
        ),
        migrations.AddConstraint(
            model_name='deductionxuser',
            constraint=models.UniqueConstraint(fields=('user', 'deduction'), name='unique_deduction_user'),
        ),
        migrations.AddConstraint(
            model_name='payrollentry',
            constraint=models.UniqueConstraint(fields=('payroll', 'user'), name='unique_payroll_entry'),
        ),
    ]
