# Generated by Django 5.0.7 on 2024-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='operator',
            field=models.CharField(choices=[('+', 'Suma'), ('-', 'Resta')], default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='payroll',
            name='includes_leaves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='includes_overtime',
            field=models.BooleanField(default=False),
        ),
    ]
