# Generated by Django 5.0.7 on 2024-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_concept_operator_payroll_includes_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='operator',
            field=models.CharField(blank=True, choices=[('+', 'Suma'), ('-', 'Resta'), (None, 'Ninguno')], default='-', max_length=1, null=True),
        ),
    ]
