# Generated by Django 5.0.7 on 2024-11-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_concept_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-payroll_id'], 'verbose_name': 'Nómina', 'verbose_name_plural': 'Nóminas'},
        ),
    ]
