# Generated by Django 5.0.7 on 2024-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='type',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('F', 'Finalizada')], default='P', max_length=1, null=True),
        ),
    ]
