# Generated by Django 5.0.7 on 2024-11-05 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A')),
                ('receiver', models.ForeignKey(db_column='receiver', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_receiver', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('sender', models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sender', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'NOTIFICATION',
                'ordering': ['-created_at'],
            },
        ),
    ]
